---

- name: add additional apt keys
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: add additional repositories
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: install dependencies
  apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose

- name: create base directory
  file:
    state: directory
    path: /opt/greenlight

- name: create docker-compose
  template:
    src: '{{ item }}'
    dest: /opt/greenlight/{{ item }}
  loop:
    - docker-compose.yml
    - greenlight.env
  notify: restart greenlight

- name: copy nginx config
  copy:
    src: greenlight.nginx
    dest: /etc/bigbluebutton/nginx/greenlight.nginx
  notify: reload nginx

- name: configure NGINX to use greenlight as default for bbb
  blockinfile:
    path: /etc/nginx/sites-available/bigbluebutton
    insertbefore: '^}'
    marker_begin: 'BEGIN GREENLIGHT'
    marker_end: 'END GREENLIGHT'
    block: |
        location = / {
            return 307 /b;
        }
  notify: reload nginx

- name: check greenlight status (allowed to fail)
  shell: >
    docker inspect greenlight-v2 | grep -q '"Status": *"running"'
  register: greenlight_is_running
  ignore_errors: true
  changed_when: false

- name: start greenlight
  command: docker-compose up -d
  args:
    chdir: /opt/greenlight
  when: greenlight_is_running is failed

- name: install database backup service
  copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/{{ item }}
  loop:
    - greenlight-backup-database.service
    - greenlight-backup-database.timer

- name: start database backup service
  service:
    name: greenlight-backup-database.timer
    state: started
    enabled: yes
